# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Authorship settings
#
title: BPKG
tagline: Lightweight Shell Package Manager

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Alert or notifications settings
#
alert:
  type: info
  title: 🎉 Happy News!
  message: The new release is out :-) <a href="https://github.com/bpkg/bpkg/releases" target="_blank">Get it NOW!</a>

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Theme settings
#
remote_theme: javanile/package-manager@main
logo: https://github.com/javanile/bpkg.javanile.org/raw/main/bpkg.png
logo_text: bpkg
primary_color: "#2d2d2d"
highlighter: rouge

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Packages settings
#
defaults:
  - scope: { path: "" }
    values: { layout: "default" }
collections:
  packages:
    output: true
    permalink: /:collection/:name

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Build settings
#
markdown: kramdown
kramdown:  
  input: GFM
