# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Authorship settings
#
title: BPKG
tagline: Lightweight Shell Package Manager

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Alert or notifications settings
#
alert:
  type: info
  title: 🎉 Happy News!
  message: The new release is out :-) <a href="https://github.com/bpkg/bpkg/releases" target="_blank">Get it NOW!</a>

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Theme settings
#
remote_theme: javanile/package-manager@main
logo: https://github.com/javanile/bpkg.javanile.org/raw/main/assets/images/bpkg.png
logo_text: bpkg
primary_color: "#2d2d2d"
highlighter: rouge
brand_font_url: "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
brand_font_family: "'Press Start 2P', system-ui"

navigation:
  - name: Get Started
    link: /get-started/
  - name: Packages
    link: /packages/
  - name: Guidelines
    link: /guidelines/
  - name: Submit Package
    link: /submit/

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Packages settings
#
suggested_command: "bpkg install {package}"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "categories"
    values:
      body_class: "page-packages"

collections:
  packages:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /:collection/:name/

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: /cat/:name/

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Build settings
#
markdown: kramdown
kramdown:  
  input: GFM
